---
title: "Interactive Census Map"
author: "Matt Khinda"
date: "10/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include = FALSE}
library(tidycensus)
library(leaflet)
library(sf)
library(tidyverse)
library(ggthemes)
library(ggspatial)
library(htmlwidgets)
library(tidytransit)
library(here)
```

```{r exploring variables, include = FALSE}
v19 <- load_variables(2019, "acs5", cache = TRUE)
View(v19)

```

```{r interactive map, echo=FALSE}
NYC_housingcost <- get_acs(geography = "tract",  state = "NY",
                           year = 2019, survey = "acs5",
                           variables = c(med_gross_rent = "B25063_001", med_owner_cost = "B25088_001",tot_units = "B25003_001", tot_owner = "B25003_002", tot_renter = "B25003_003"),
                           output = "wide", geometry = TRUE) 

NYC_housingcost <- NYC_housingcost %>%
  select(-med_gross_rentM, -med_owner_costM, -tot_ownerM, -tot_renterM, - tot_unitsM) %>%
  mutate(pct_renter = round((tot_renterE/tot_unitsE)*100, 1)) %>%
  mutate(pct_owner = round((tot_ownerE/tot_unitsE)*100, 1)) %>%
  mutate(pays_more = ifelse(med_owner_costE > med_gross_rentE, "Owners pay more", "Renters pay more")
           ) %>%
  mutate(med_owner_costE =  replace_na(med_owner_costE, "Unknown")) %>%
  mutate(pays_more =  replace_na(pays_more, "Unknown")) %>%
  st_transform("WGS84")
  
NYC_boundaries <- read_sf(here("Data", "NYCBoundaries.geojson")) %>%
  st_transform("WGS84")

NYC_housingcost_clipped <- NYC_housingcost[NYC_boundaries,]


NYC_hc_palette <- colorFactor(palette = c('#FF7F58', '#611831', 'white'),
  domain = NYC_housingcost_clipped$pays_more
)

NYC_hc_map <- leaflet(NYC_housingcost_clipped) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(fillColor = ~NYC_hc_palette(pays_more), weight = 0.45, color = "white", fillOpacity = 0.8,
              highlightOptions = highlightOptions(fillColor = "#FDFF64", fillOpacity = 0.8),
              label = NYC_housingcost_clipped$NAME,
              popup = paste("Median Monthly Owner Costs: ", " $",NYC_housingcost_clipped$med_owner_costE, "<br/>",
                            "Median Monthly Gross Rent: ", " $",NYC_housingcost_clipped$med_gross_rentE, "<br/>",
                            "Total Owners: ", NYC_housingcost_clipped$tot_ownerE, " (", NYC_housingcost_clipped$pct_owner,"%)", "<br/>",
                            "Total Renters: ", NYC_housingcost_clipped$tot_renterE," (", NYC_housingcost_clipped$pct_renter,"%)", sep = "")) %>%
  addLegend("bottomright", pal = NYC_hc_palette, values = ~pays_more,
    title = "Who Pays More in Monthly Housing Costs?",
    opacity = 1)

NYC_hc_map

```
